name: SCA Agent-Based Scan
on: 
  workflow_dispatch:
  pull_request:

permissions: write-all

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: SCA Agent-Based Scan
    steps:
      - name: SCA Agent Scan
        run: |             
             export SRCCLR_API_TOKEN=${{ secrets.SRCCLR_API_TOKEN }}
             curl -sSL https://download.sourceclear.com/ci.sh | bash -s - scan --update-advisor --allow-dirty --recursive
